### ISSUE TITLE
Сделать исчерпывающий список статей про извлечение смысла

### ISSUE THREAD

**Issue by selivanov-as** [selivanov-as/ml-text-highlights#1]
Надо поискать статьи про извлечение смысла из текста.
Давайте опубликуем их [здесь](https://github.com/selivanov-as/ml-text-highlights/wiki/Список-статей-про-извлечение-смысла)

**Comment by selivanov-as** [comment]
Продолжаем пополнять список статей

**Comment by isaintnik** [comment]
Вроде бы добили.
