### ISSUE TITLE
Обучение Glove/word2vec

### ISSUE THREAD

**Issue by bulgakovk** [selivanov-as/ml-text-highlights#21]
1. Найти обученную модель (без семантических весов)
2. Если не найдется, загнать русский корпус в Glove/Word2vec и обучиться
3. Попробовать использовать полученные результаты (норму слова, т.е. оценку окна из 5 следующих/предыдущих слов по текущему слову)

**Comment by selivanov-as** [comment]
Договорились обучится на корпусе вики https://github.com/selivanov-as/ml-text-highlights/issues/27

**Comment by selivanov-as** [comment]
Никита на встрече говорил про L2 норму слова..

**Comment by selivanov-as** [comment]
Добавить в исследованию
- rusvectores
- vgramm

**Comment by selivanov-as** [comment]
+ Опубликовать результаты

**Comment by selivanov-as** [comment]
Максим:
Тут можно посмотреть результаты выделения по разным ворд2векам. На мой взгляд, во всех вариантах плохо.
 https://github.com/selivanov-as/ml-text-highlights/tree/feat/word2vec_norm_highlighting/w2v/examples

**Comment by selivanov-as** [comment]
Имхо, все же стоит чуть побольше подебажить, посмотреть, почему некоторые слова не выделяются, добавить знания о том какие слова в документе встретились в наблюдаемом окне

**Comment by selivanov-as** [comment]
Тут можно посмотреть результаты выделения по разным ворд2векам. На мой взгляд, во всех вариантах плохо.
 https://github.com/selivanov-as/ml-text-highlights/tree/feat/word2vec_norm_highlighting/w2v/examples
