### ISSUE TITLE
Валидация POS в pymorphy2

### ISSUE THREAD

**Issue by bulgakovk** [selivanov-as/ml-text-highlights#25]
- [x] Получить все токены википедии

- [x]  Натравить POS теггер из pymorphy2 на википедию. Проанализировать самые популярные части речи и разные слова (мой, пожалуйста) в частности.

**Comment by selivanov-as** [comment]
Не поговорили о результатах

**Comment by selivanov-as** [comment]
- pymorphy2 на всю википедию натравить не получилось, опять проблемы с системными ошибками. На небольшой части (5%) проблем никаких не увидел. Могу попозже выгрузить файлик куда-нибудь посмотреть.

**Comment by selivanov-as** [comment]
Нужно написать инструкцию, а я попробую запустить все у себя

**Comment by selivanov-as** [comment]
https://github.com/selivanov-as/ml-text-highlights/commit/b54cdb43c16c25b10dd273eed15c3085170d7b75

**Comment by selivanov-as** [comment]
результаты:

* "сырой" счетчик: https://yadi.sk/d/7nYfEqFHcxPF1Q
* json: https://yadi.sk/d/0euBtYb_6_Xi4A
