### ISSUE TITLE
Выбрать победителя по хайлайтам 

### ISSUE THREAD

**Issue by selivanov-as** [selivanov-as/ml-text-highlights#51]
- Провести поединки
- Рассчитать результаты
- Опубликовать результаты на вики

**Comment by isaintnik** [comment]
Выбрали победителя!!!
Победил самый навороченный вариант.
https://github.com/selivanov-as/ml-text-highlights/wiki/Результаты-выбора-лучшего-алгоритма-на-Яндекс-Толоке
